#_quarto.yml set-up was inspired by/adapted from Sam Shanny-Csik and available through this link: https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide 
#Furthermore, organisation ideas such as assets folder inspired by Damien Dupre, accessible through here: https://damien-dupre.github.io/ 
#For drop menu, code explained, it was given through quarto: https://quarto.org/docs/websites/website-navigation.html
project:
  type: website
  output-dir: docs

website:
  title: "Lisa Lucky"
  favicon: assets/favicon1.png
  navbar:
    title: false
    logo: assets/logo6.png
    alt: "Lisa Lucky"
    href: "/"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: CV
        menu:
          - href: english-cv.pdf
            text: English Version
          - href: german-cv.pdf
            text: German Version
      - href: /projects1/index.html
        text: Projects
        
      - href: /blog/index.html
        text: Blog


  page-footer:
    left: Copyright 2025, Lisa Lucky
    right: 
    - icon: github
      href: https://github.com/lisalucks
    - icon: linkedin
      href: https://www.linkedin.com/in/lisa-lucky-157222358/


format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full



