project:
  type: website
  output-dir: docs

website:
  title: "Lisa Lucky"
  favicon: assets/favicon1.png
  navbar:
    title: false
    logo: assets/logo6.png
    alt: "Lisa Lucky"
    href: "/"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: CV
        menu:
          - href: english-cv.pdf
            text: English Version
          - href: german-cv.pdf
            text: German Version
      - href: projects1/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog

  page-footer:
    left: Copyright 2025, Lisa Lucky
    right: 
    - icon: github
      href: https://github.com/lisalucks
    - icon: linkedin
      href: https://www.linkedin.com/in/lisa-lucky-157222358/


format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full



