project:
  type: website
  output-dir: docs

website:
  title: "Lisa Lucky"
  favicon: assets/favicon1.png
  navbar:
    title: false
    logo: assets/logo6.png
    alt: "Lisa Lucky"
    href: "/"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: CV
        menu:
          - href: english-cv.pdf
            text: English Version
          - href: german-cv.pdf
            text: German Version
      - href: projects1/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



