---
title: Thoughts After Completing the Data Analytics Specialism
description: I talk reflectively about completing the data analytics specialism in DCU and how this will shape and impact my future career Below, I have also included some forms of media which inspired me, thus allowing me to stay diligent with my efforts and expanding on my technical abilities.
date: "4/22/2025"
toc: true
author: Lisa Lucky, CareerFoundry, Visual Studio Code & Adam Finer
categories:
    - Reflective Thinking
    - Personal Entry
---

> For my final year, I opted for data analytics as my specialism. I previously enjoyed the module "Business Analytics" in my second year and was interested in coding outside of school, which is why I made this decision. In the first semester, we had the module "Data Visualisation and Programming," where we worked with three tools heavily discussed in the data analytics world: SQL, Python, and Power BI. Of course, it was challenging, but it was exhilarating when I could finally get a block of code to work or convey my exact thoughts through a visualisation, which is not easy. 

> Fast-forward to the second semester, I am building a website (something I never imagined I could do) and have built machine learning algorithms to train a dataset. The specialism was incredibly useful and allowed me to test and become proficient in most fields required of me after graduation. I will be able to walk into the industry with experience, rather than arriving empty-handed, making me a promising candidate willing to progress further. 

### Data Analytics and its importance (CareerFoundry)
I have embedded a video below about data analytics and its importance in today's world. This excites me to join the industry and know that I will be making an impact no matter what. After Candidly Vivian's [day in the life of a data scientist](projectblog_1.qmd) video, this was the introductory video to ensure I fully knew what to expect. 

```{=html}
<iframe src= "https://www.youtube.com/embed/yZvFH7B6gKI?si=TikxMNK73egMPrFS" width="700"
height= "400"></iframe>
```

### Building a website: code with me (Steph Ran)
My site and other videos show that making something aesthetically pleasing is important to me. As I previously used the code editor "Spyder" in my first semester, I worried that switching to VS Code may have disadvantaged me. Especially when I heard others around me who had more experience with it. Now I have created my website (which you are currently on!), which shows how far I've come. This was a nice introductory video for me to get excited about website building, from seeing the VS Code in the video to seeing her thoughtfulness in the web design. I started to get better encouraged. Motivation is motivation, whilst the video is not too overly informative, it was an ice breaker! 

```{=html}
<iframe src= "https://www.youtube.com/embed/ac-rvXHopbw?si=vxkLFwzpBUEimhkv" width="700"
height= "400"></iframe>
```

### The video I watched before the VS Code Lecture (Visual Studio Code)

Eager to ensure I was not left behind and could follow the lecture, I watched this video to get started. Luckily, the slide content for the next class was available beforehand, so I did look over it too! Here, I finally understood how incredible Git is and made me connect the dots regarding how this would play into my assignment. 

```{=html}
<iframe src= "https://www.youtube.com/embed/i_23KUAEtUM?si=Xzux6guQ004GZB2F" width="700"
height= "400"></iframe>

